### ISSUE TITLE
 smtp_per_user does not use the correct smtp linked to user

### ISSUE THREAD

**Issue by pvanthony** [boolit-team/base-crm-sale#1]
Installed the module in the addons folder. Setup the outgoing servers and linked it to the respective users. Logged in as the users and sent out emails.

Unfortunately it is just using one smtp server for all users when it should be using the smtp server for the respective user.

Is there anything else I should check? Did I miss something?

Need advice. Hope I can get some help.

Downloaded the module from https://www.odoo.com/apps.

**Comment by oerp-odoo** [comment]
Hello,
it seems method's internals of sending mail changed and user id was always returned as administrator. So that's why it was not finding specific SMTP server with that user. Now I fixed it by changing source where that ID is get from. Fix below:

https://github.com/oerp-odoo/base-crm-sale/commit/543b9bb2835ecc40fba24847fe67474f0fb5b3ce

If you update that module, it should get those changes (will need a server restart)

**Comment by pvanthony** [comment]
On 03/09/2015 07:54 PM, Andrius Laukavičius wrote:

> it seems method's internals of sending mail changed and user id was
> always returned as administrator. So that's why it was not finding
> specific SMTP server with that user. Now I fixed it by changing source
> where that ID is get from. Fix below:
> 
> 543b9bb
> https://github.com/oerp-odoo/base-crm-sale/commit/543b9bb2835ecc40fba24847fe67474f0fb5b3ce

Thank you very much for looking into this. I do appreciate it.

> If you update that module, it should get those changes (will need a
> server restart)

I uninstalled the version 8.0.0.2 and installed version 8.0.0.3. 
Assigned the users to the respective outgoing smtp servers. Then 
restarted odoo. Unfortunately it still did not work.

Then did a git pull to get the latest version of odoo 8. Then started 
the odoo with -u all to update the database and modules. I am very sorry 
to say that it still does not work.

Did I miss anything? Should I need to do anything else?

Your advice is greatly appreciated.

## 

P.V.Anthony

**Comment by oerp-odoo** [comment]
Its hard to tell whats wrong on your end. Does it send for example with that SMTP server you want if for example you would change priority to highest (for that server)? To see if it sends using that server. Also if you run server in developing environment (for example from directly from terminal), you can simply check if it finds you UID (user id). Simply modify smtp_per_user.py method 'send_email' and try to print this one in that method writing this `print self.env.context.get('uid'))`.

**Comment by pvanthony** [comment]
On 03/10/2015 02:52 PM, Andrius Laukavičius wrote:

> Its hard to tell whats wrong on your end. Does it send for example with
> that SMTP server you want if for example you would change priority to
> highest (for that server)? To see if it sends using that server.

Once again thank you for replying. Yes you are correct. It sends the 
email from the server I want if the server is set to a higher priority.

> Also if
> you run server in developing environment (for example from directly from
> terminal), you can simply check if it finds you UID (user id). Simply
> modify smtp_per_user.py method 'send_email' and try to print this one in
> that method writing this |print self.env.context.get('uid'))|.

I will try the above later and get back to you with the results.

## 

P.V.Anthony

**Comment by pvanthony** [comment]
On 03/10/2015 02:52 PM, Andrius Laukavičius wrote:

> Also if
> you run server in developing environment (for example from directly from
> terminal), you can simply check if it finds you UID (user id). Simply
> modify smtp_per_user.py method 'send_email' and try to print this one in
> that method writing this |print self.env.context.get('uid'))|.

Did the modification in smtp_per_user.py in the 'send_email' method. 
Place the code "print self.env.context.get('uid')" just above the if 
statement. Then ran the server in developing mode by running it from 
command line.

The result after sending an email for the print statement was "None".

Seems that it cannot get the user id. What should I do from here? Did I 
miss some step?

## 

P.V.Anthony

**Comment by oerp-odoo** [comment]
I checked this on my test and production servers. Both return `uid` for current user. It seems for some reason on your end, context do not pass `uid`. Can you try printing whole context dictionary? To see if any context is passed at all?
You can write such print statement:
`print self.env.context`

**Comment by pvanthony** [comment]
On 03/12/2015 04:11 PM, Andrius Laukavičius wrote:

> I checked this on my test and production servers. Both return |uid| for
> current user. It seems for some reason on your end, context do not pass
> |uid|. Can you try printing whole context dictionary? To see if any
> context is passed at all?
> You can write such print statement:
> |print self.env.context|

Thank you for continuing to help me. I really do appreciate it.

Here is the output of the dictionary.

Print the whole dictionary:  {'default_res_id': 65, 
'mail_post_autofollow_partner_ids': [], 'default_model': 'crm.lead', 
'model_name': u'Lead/Opportunity', 'mail_read_set_read': True, 
'mail_post_autofollow': True}

## 

P.V.Anthony

**Comment by pvanthony** [comment]
Just tried the following module and it seems to work. Just did the install and simple testing.
https://www.odoo.com/apps/modules/8.0/tko_mail_smtp_per_user/

**Comment by oerp-odoo** [comment]
@pvanthony  This problem is now fixed on our module too  https://github.com/oerp-odoo/base-crm-sale/commit/e39d31f9ec8e5951166b210ac94f6432682b229c

The difference between these modules is that for some reason that module you linked, forces `reply_to`, to always take email_from from `mail` record. This might cause problems if used with catch all (because odoo automatically chooses `reply_to`, if it is for example written from lead to reply to lead directly).
