### ISSUE TITLE
Sale Fast Confirm - Multiple Orders

### ISSUE THREAD

**Issue by mfaheemkhan6** [boolit-team/base-crm-sale#2]
Sale fast confirm module is for fast processing of sale orders. But we can only confirm one order at a time. It is better if there is a button in more menu to process multiple orders at once. Hope that you will add this feature.

**Comment by oerp-odoo** [comment]
Hello @mfaheemkhan6 

I want to notify that I just implemented this functionality. This might come a bit late, but didn't have much spare time to do it. You can download newest version (don't forget to upgrade module).

**Comment by mfaheemkhan6** [comment]
Thanks @oerp-odoo for this improvement. It is very helpful for me. Can you please upgrade it to support purchase order as well?

**Comment by oerp-odoo** [comment]
@mfaheemkhan6  unfortunately, no development time is granted for such functionality (at least for now).
